### ISSUE TITLE
CelebA_VAE_small_8.h5 file error

### ISSUE THREAD

**Issue by soroosh-rz** [hse-aml/bayesian-methods-for-ml#4]
For the final project, the CelebA_VAE_small_8.h5 file can not be downloaded in the colab. I tried to load weight for the final project but I received the following error:

![colab](https://user-images.githubusercontent.com/16475747/59936139-4be87a00-941d-11e9-90eb-9737f9000877.PNG)

I looked at the course github and there is no h5 file there. It may have something to do with the recent update on the course github! Could you please fix this or help to work around it? Thanks

**Comment by danpol** [comment]
Hi! We moved the CelebA_VAE_small_8.h5 file to another location, please try downloading the notebook file again and running download function from scratch. We will re-upload h5 back to LFS to two weeks for smoother migration.

**Comment by soroosh-rz** [comment]
Ok. Thanks. I downloaded the file manually (wget) and it works!
